# Generated by setup.sh. Source this file to use the CoDesign runner environment.
export CODESIGN_VENV_DIR="/root/.venvs/codesign"
export CODESIGN_RUNNER_PYTHON="/root/.venvs/codesign/bin/python"
export CODESIGN_PYTHON="/root/.venvs/codesign/bin/python"

# IsaacLab bootstrap files often alias python/pip to Isaac Sim. Clear those so
# the CoDesign runner venv wins in interactive shells.
unalias python python3 pip pip3 2>/dev/null || true

if [[ -f "/root/.venvs/codesign/bin/activate" ]]; then
  # Use the standard activation script so shells also show the active venv.
  source "/root/.venvs/codesign/bin/activate"
else
  export VIRTUAL_ENV="/root/.venvs/codesign"
  case ":$PATH:" in
    *:"/root/.venvs/codesign/bin":*) ;;
    *) export PATH="/root/.venvs/codesign/bin:$PATH" ;;
  esac
fi

export CODESIGN_RUNNER_PYTHON="/root/.venvs/codesign/bin/python"
export CODESIGN_PYTHON="/root/.venvs/codesign/bin/python"
export CODESIGN_ISAAC_PYTHON="/root/isaaclab/_isaac_sim/python.sh"
export CODESIGN_XACRODOC="/root/.venvs/codesign/bin/xacrodoc"
